# Generated by Django 5.0.2 on 2025-06-08 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('fixing', 'Fixing'), ('fixed', 'Fixed'), ('failed', 'Failed')], default='detected', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('analysis_result', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='logs.log')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bugs_bug_user_id_f915f1_idx'), models.Index(fields=['severity'], name='bugs_bug_severit_9ad1a4_idx'), models.Index(fields=['detected_at'], name='bugs_bug_detecte_3fc925_idx')],
            },
        ),
    ]
