# Generated by Django 5.0.1 on 2025-12-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
        ('github_integration', '0002_alter_githubrepository_github_app'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='github_integration.githubrepository'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='logs.log'),
        ),
    ]
