# Generated by Django 5.0.1 on 2025-10-10 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('installation_id', models.BigIntegerField(unique=True)),
                ('app_id', models.BigIntegerField()),
                ('target_id', models.BigIntegerField()),
                ('target_type', models.CharField(max_length=20)),
                ('permissions', models.JSONField(default=dict)),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suspended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_github_apps', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub App',
                'verbose_name_plural': 'GitHub Apps',
            },
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('private', models.BooleanField(default=False)),
                ('fork', models.BooleanField(default=False)),
                ('html_url', models.URLField()),
                ('clone_url', models.URLField()),
                ('ssh_url', models.URLField()),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('syncing', 'Syncing'), ('error', 'Error')], default='active', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('auto_analyze', models.BooleanField(default=True)),
                ('analyze_branches', models.JSONField(default=list)),
                ('analyze_paths', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='github_integration.githubapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Repository',
                'verbose_name_plural': 'GitHub Repositories',
            },
        ),
        migrations.CreateModel(
            name='GitHubWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=255)),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='github_integration.githubrepository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Webhook',
                'verbose_name_plural': 'GitHub Webhooks',
            },
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['user', 'status'], name='github_inte_user_id_3a1fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['github_app', 'status'], name='github_inte_github__170ea8_idx'),
        ),
    ]
