# Generated by Django 5.0.1 on 2025-12-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='github_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='github_integration.githubapp'),
        ),
    ]
