# Generated by Django 5.0.2 on 2025-06-17 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('reviewed', 'Reviewed'), ('applied', 'Applied'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('original_file_path', models.CharField(max_length=255)),
                ('original_code', models.TextField()),
                ('patched_code', models.TextField()),
                ('diff', models.TextField(help_text='Unified diff format of the changes')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('review_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='bugs.bug')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patch',
                'verbose_name_plural': 'Patches',
                'ordering': ['-created_at'],
            },
        ),
    ]
